# Generated by Django 4.2.2 on 2023-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
