# Generated by Django 4.2.2 on 2023-06-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0002_licence_licences1'),
    ]

    operations = [
        migrations.CreateModel(
            name='licences3',
            fields=[
                ('num_matricule_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('Matiere', models.CharField(max_length=25)),
                ('heure_debut', models.IntegerField(default=1)),
                ('heure_fin', models.IntegerField(default=1)),
                ('jours', models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi')], default='lundi', max_length=12)),
                ('date_debut', models.DateField(blank=True)),
                ('date_fin', models.DateField(blank=True)),
                ('Annee_Academie', models.ForeignKey(default='L3', on_delete=django.db.models.deletion.CASCADE, to='projetept.licence')),
                ('semestres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='licences2',
            fields=[
                ('num_matricule_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('Matiere', models.CharField(max_length=25)),
                ('heure_debut', models.IntegerField(default=1)),
                ('heure_fin', models.IntegerField(default=1)),
                ('jours', models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi')], default='lundi', max_length=12)),
                ('date_debut', models.DateField(blank=True)),
                ('date_fin', models.DateField(blank=True)),
                ('Annee_Academie', models.ForeignKey(default='L2', on_delete=django.db.models.deletion.CASCADE, to='projetept.licence')),
                ('semestres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre')),
            ],
        ),
    ]
