# Generated by Django 4.2.2 on 2023-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0003_licences3_licences2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences1',
            name='date_fin',
            field=models.DateField(blank=True),
        ),
    ]
