# Generated by Django 4.2.2 on 2023-06-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0004_alter_licences1_date_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licences1',
            old_name='heure_debut',
            new_name='Heure_Restant',
        ),
        migrations.RenameField(
            model_name='licences1',
            old_name='heure_fin',
            new_name='Heure_Total',
        ),
        migrations.RenameField(
            model_name='licences1',
            old_name='jours',
            new_name='Jour_De_Cour',
        ),
        migrations.RenameField(
            model_name='licences2',
            old_name='heure_debut',
            new_name='Heure_Restant',
        ),
        migrations.RenameField(
            model_name='licences2',
            old_name='heure_fin',
            new_name='Heure_Total',
        ),
        migrations.RenameField(
            model_name='licences2',
            old_name='jours',
            new_name='Jour_De_Cour',
        ),
        migrations.RenameField(
            model_name='licences3',
            old_name='heure_debut',
            new_name='Heure_Restant',
        ),
        migrations.RenameField(
            model_name='licences3',
            old_name='heure_fin',
            new_name='Heure_Total',
        ),
        migrations.RenameField(
            model_name='licences3',
            old_name='jours',
            new_name='Jour_De_Cour',
        ),
        migrations.RemoveField(
            model_name='licences1',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='licences1',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='licences2',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='licences2',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='licences3',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='licences3',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='licences1',
            name='Heure_debut',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licences1',
            name='Heure_fin',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licences2',
            name='Heure_debut',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licences2',
            name='Heure_fin',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licences3',
            name='Heure_debut',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licences3',
            name='Heure_fin',
            field=models.TimeField(blank=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licences2',
            name='Annee_Academie',
            field=models.ForeignKey(default='L1', on_delete=django.db.models.deletion.CASCADE, to='projetept.licence'),
        ),
        migrations.AlterField(
            model_name='licences3',
            name='Annee_Academie',
            field=models.ForeignKey(default='L1', on_delete=django.db.models.deletion.CASCADE, to='projetept.licence'),
        ),
    ]
