# Generated by Django 4.2.2 on 2023-06-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0005_rename_heure_debut_licences1_heure_restant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrateur',
            fields=[
                ('Num_Matricule', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Nom_Professeur', models.CharField(max_length=20)),
                ('Prenom_Professeur', models.CharField(max_length=20)),
                ('Mot_De_Passe', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('Num_Matricule', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Nom_Etudiant', models.CharField(max_length=20)),
                ('Prenom_Etudiant', models.CharField(max_length=20)),
                ('Mot_De_Passe', models.CharField(default='', max_length=20)),
                ('Annee_Academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.licence')),
            ],
        ),
    ]
