# Generated by Django 4.2.2 on 2023-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0007_alter_administrateur_num_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='id',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=1, primary_key=True, serialize=False),
        ),
    ]
