# Generated by Django 4.2.2 on 2023-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0008_alter_semestre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Annee_Academy',
        ),
        migrations.RemoveField(
            model_name='licences1',
            name='Annee_Academie',
        ),
        migrations.RemoveField(
            model_name='licences1',
            name='semestres',
        ),
        migrations.RemoveField(
            model_name='licences2',
            name='Annee_Academie',
        ),
        migrations.RemoveField(
            model_name='licences2',
            name='semestres',
        ),
        migrations.RemoveField(
            model_name='licences3',
            name='Annee_Academie',
        ),
        migrations.RemoveField(
            model_name='licences3',
            name='semestres',
        ),
        migrations.DeleteModel(
            name='licence',
        ),
    ]
