# Generated by Django 4.2.2 on 2023-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0009_remove_etudiant_annee_academy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences1',
            name='Matiere',
            field=models.CharField(default='', max_length=25),
        ),
    ]
