# Generated by Django 4.2.2 on 2023-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0010_alter_licences1_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='autre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jour_De_Cour', models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi')], default='lundi', max_length=12)),
                ('jour_semaine', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='licences1',
            name='Jour_De_Cour',
        ),
        migrations.RemoveField(
            model_name='licences2',
            name='Jour_De_Cour',
        ),
        migrations.RemoveField(
            model_name='licences3',
            name='Jour_De_Cour',
        ),
    ]
