# Generated by Django 4.2.2 on 2023-06-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0011_autre_remove_licences1_jour_de_cour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='licences1',
            new_name='licences',
        ),
        migrations.DeleteModel(
            name='licences2',
        ),
        migrations.DeleteModel(
            name='licences3',
        ),
    ]
