# Generated by Django 4.2.2 on 2023-06-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0013_autre_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='licences',
            name='semestres',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre'),
            preserve_default=False,
        ),
    ]
