# Generated by Django 4.2.2 on 2023-06-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0015_delete_autre_licences_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='autre',
            fields=[
                ('Jour_De_Cour', models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi')], default='lundi', max_length=12, primary_key=True, serialize=False)),
                ('jour_semaine', models.DateField(blank=True)),
                ('filiere', models.CharField(choices=[('IM', 'IM'), ('GL', 'GL'), ('SI', 'SI'), ('IA', 'IA'), ('SAOIT', 'SAOIT')], default='IM', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='licences',
            name='jour',
            field=models.ForeignKey(default='lundi', on_delete=django.db.models.deletion.CASCADE, to='projetept.autre'),
        ),
    ]
