# Generated by Django 4.2.2 on 2023-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0016_autre_licences_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences',
            name='Notification',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
