# Generated by Django 4.2.2 on 2023-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0017_alter_licences_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='licences',
            name='Nom_Prenom_Prof',
            field=models.CharField(default='', max_length=25),
        ),
    ]
