# Generated by Django 4.2.2 on 2023-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0018_licences_nom_prenom_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences',
            name='Notification',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
