# Generated by Django 4.2.2 on 2023-06-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='licences',
            fields=[
                ('num_matricule_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('Matiere', models.CharField(default='', max_length=25)),
                ('Nom_Prenom_Prof', models.CharField(default='', max_length=25)),
                ('Heure_Total', models.IntegerField(default=1)),
                ('Heure_Restant', models.IntegerField(default=1)),
                ('Heure_debut', models.TimeField(blank=True)),
                ('Heure_fin', models.TimeField(blank=True)),
                ('Notification', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('Jour_De_Cour', models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi')], default='lundi', max_length=12)),
                ('Date_semaine', models.DateField(blank=True)),
                ('filiere', models.CharField(choices=[('IM', 'IM'), ('GL', 'GL'), ('SI', 'SI'), ('IA', 'IA'), ('SAOIT', 'SAOIT')], default='IM', max_length=20)),
                ('semestres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('Num_Matricule', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Nom_Etudiant', models.CharField(default='', max_length=20)),
                ('Prenom_Etudiant', models.CharField(default='', max_length=20)),
                ('Mot_De_Passe', models.CharField(default='', max_length=20)),
                ('numero', models.IntegerField(blank=True)),
                ('semestres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre')),
            ],
        ),
    ]
