# Generated by Django 4.2.2 on 2023-06-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrations',
            fields=[
                ('Num_Matricule', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Nom_Membre', models.CharField(default='', max_length=20)),
                ('Prenom_Membre', models.CharField(default='', max_length=20)),
                ('Mot_De_Passe', models.CharField(default='', max_length=20)),
                ('numero', models.IntegerField(blank=True)),
                ('semestres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetept.semestre')),
            ],
        ),
    ]
