# Generated by Django 4.2.2 on 2023-06-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetept', '0002_administrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrations',
            name='semestres',
        ),
    ]
